name: SimplePlayerUtils
version: '${project.version}'
main: adhdmc.simpleplayerutils.SimplePlayerUtils
api-version: 1.19
authors: [ Rhythmic, Peashooter101 ]
description: Utils for players
softdepend:
  - PlaceholderAPI
commands:
  spureload:
    description: reloads the configuration
    permission: spu.reload
  hat:
    description: puts something on your head
    permission: spu.command.hat
  afk:
    description: allows afk toggling
    permission: spu.command.afk
  fly:
    description: allows creative flight
    permission: spu.command.fly
  flyspeed:
    description: allows changing flyspeed
    permission: spu.command.flyspeed
    aliases: [fspeed]
  walkspeed:
    description: allows changing walkspeed
    permission: spu.command.walkspeed
    aliases: [wspeed]
  anvil:
    description: opens an anvil
    permission: spu.command.anvil
  cartography:
    description: opens a cartography table
    permission: spu.command.cartography
    aliases: [cart, carto]
  craft:
    description: opens a crafting menu
    permission: spu.command.crafting
    aliases: [workbench, wb, bench]
  grindstone:
    description: opens a grindstone
    permission: spu.command.grindstone
    aliases: [grind]
  loom:
    description: opens a loom
    permission: spu.command.loom
  smithing:
    description: opens a smithing table
    permission: spu.command.smithing
    aliases: [smith]
  stonecutter:
    description: opens a stonecutter
    permission: spu.command.stonecutter
  enderchest:
    description: opens an enderchest
    permission: spu.command.enderchest
    aliases: [ec, ender, end]
  trash:
    description: opens an inventory that will delete items on closing
    permission: spu.command.trash
    aliases: [disposal, garbage, lava]
  rename:
    description: renames an item
    permission: spu.command.rename
  repair:
    description: repair an item, or many
    permission: spu.command.repair
permissions:
  spu.reload:
    description: Reloads the Simple Player Utils config and locale
    default: op
  spu.command.hat:
    description: Lets you put something on your head
    default: op
  spu.command.afk:
    description: Allows a player to toggle their AFK status
    default: op
  spu.command.other.afk:
    description: Allows a player to toggle other players' afk status
    default: op
  spu.command.fly:
    description: Allows a player to toggle their personal flight
    default: op
  spu.command.other.fly:
    description: Allows a player to toggle other players' flight
    default: op
  spu.command.flyspeed:
    description: Allows a player to set their own flyspeed
    default: op
  spu.command.other.flyspeed:
    description: Allows a player to set other players' flyspeeds
    default: op
  spu.command.walkspeed:
    description: Allows a player to set their own walkspeed
    default: op
  spu.command.other.walkspeed:
    description: Allows a player to set other players' walkspeeds
    default: op
  spu.command.inventory.anvil:
    description: Allows a player to use the anvil menu
    default: op
  spu.command.other.inventory.anvil:
    description: Allows a player to open an anvil menu for another player
    default: op
  spu.command.inventory.cartography:
    description: Allows a player to open a cartography table
    default: op
  spu.command.other.inventory.cartography:
    description: Allows a player to open a cartography table for another player
    default: op
  spu.command.inventory.crafting:
    description: Allows a player to open a crafting menu
    default: op
  spu.command.other.inventory.crafting:
    description: Allows a player to open a crafting menu for other players
    default: op
  spu.command.inventory.grindstone:
    description: Allows a player to open a grindstone
    default: op
  spu.command.other.inventory.grindstone:
    description: Allows a player to open a grindstone for another player
    default: op
  spu.command.inventory.loom:
    description: Allows a player to open a loom
    default: op
  spu.command.other.inventory.loom:
    description: Allows a player to open a loom for another player
    default: op
  spu.command.inventory.smithing:
    description: Allows a player to open a smithing table
    default: op
  spu.command.other.inventory.smithing:
    description: Allows a player to open a smithing table for another player
    default: op
  spu.command.inventory.stonecutter:
    description: Allows a player to open a stonecutter
    default: op
  spu.command.other.inventory.stonecutter:
    description: Allows a player to open a stonecutter for another player
    default: op
  spu.command.inventory.enderchest:
    description: Allows a player to open their own enderchest
    default: op
  spu.command.other.inventory.enderchest:
    description: Allows a player to open another player's enderchest for them (does not look into their enderchest)
    default: op
  spu.command.trash:
    description: Allows a player to open an inventory to throw away items
    default: op
  spu.command.other.trash:
    description: Allows a player to open a trash menu for other players
    default: op
  spu.command.rename.basic:
    description: Allows a player to /rename their items, with no color codes
    default: op
  spu.command.rename.minimessage:
    description: Allows a player to /rename their items using minimessage formatting
    default: op
  spu.command.rename.character.max.bypass:
    description: Allows a player to bypass the configured max character value for /rename
    default: op